### ISSUE TITLE
Issue - A person can vote multiple times

### ISSUE THREAD

**Issue by Raulvv** [DECODEproject/wallet#5]
If a person tries to sign the same petition more than one time, is able to do it.

In order to prevent this to happen, we need to implement Coconut to verify that a person with a credential assigned doesn't sign more than once (double spending problem).

You can see an example of a coconut contract for Chainspace that *DOESN'T* use Zenroom at [coconut chainspace contract](https://github.com/asonnino/coconut)

**Comment by jaromil** [comment]
Solved in current Zenroom implementation of coconut (array of zetas)
